/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildersIndexRouteImport } from './routes/builders/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectHeroHomesRouteImport } from './routes/project.hero-homes'
import { Route as PlacesNewChandigarhRouteImport } from './routes/places.new-chandigarh'
import { Route as BuildersSlugRouteImport } from './routes/builders.$slug'
import { Route as BuilderOmaxeRouteImport } from './routes/builder.omaxe'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AdminUnitTypesIndexRouteImport } from './routes/admin.unit-types.index'
import { Route as AdminRelationshipsIndexRouteImport } from './routes/admin.relationships.index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminPlacesIndexRouteImport } from './routes/admin.places.index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin.media.index'
import { Route as AdminInfrastructureIndexRouteImport } from './routes/admin.infrastructure.index'
import { Route as AdminContentHealthIndexRouteImport } from './routes/admin.content-health.index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin.categories.index'
import { Route as AdminBuildersIndexRouteImport } from './routes/admin.builders.index'
import { Route as AdminAmenitiesIndexRouteImport } from './routes/admin.amenities.index'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'
import { Route as AdminUnitTypesNewRouteImport } from './routes/admin.unit-types.new'
import { Route as AdminUnitTypesIdRouteImport } from './routes/admin.unit-types.$id'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminProjectsIdRouteImport } from './routes/admin.projects.$id'
import { Route as AdminPlacesNewRouteImport } from './routes/admin.places.new'
import { Route as AdminPlacesIdRouteImport } from './routes/admin.places.$id'
import { Route as AdminInfrastructureNewRouteImport } from './routes/admin.infrastructure.new'
import { Route as AdminInfrastructureIdRouteImport } from './routes/admin.infrastructure.$id'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin.categories.new'
import { Route as AdminCategoriesIdRouteImport } from './routes/admin.categories.$id'
import { Route as AdminBuildersNewRouteImport } from './routes/admin.builders.new'
import { Route as AdminBuildersIdRouteImport } from './routes/admin.builders.$id'
import { Route as AdminAmenitiesNewRouteImport } from './routes/admin.amenities.new'
import { Route as AdminAmenitiesIdRouteImport } from './routes/admin.amenities.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersIndexRoute = BuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectHeroHomesRoute = ProjectHeroHomesRouteImport.update({
  id: '/project/hero-homes',
  path: '/project/hero-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesNewChandigarhRoute = PlacesNewChandigarhRouteImport.update({
  id: '/places/new-chandigarh',
  path: '/places/new-chandigarh',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersSlugRoute = BuildersSlugRouteImport.update({
  id: '/builders/$slug',
  path: '/builders/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderOmaxeRoute = BuilderOmaxeRouteImport.update({
  id: '/builder/omaxe',
  path: '/builder/omaxe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUnitTypesIndexRoute = AdminUnitTypesIndexRouteImport.update({
  id: '/unit-types/',
  path: '/unit-types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelationshipsIndexRoute = AdminRelationshipsIndexRouteImport.update({
  id: '/relationships/',
  path: '/relationships/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesIndexRoute = AdminPlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfrastructureIndexRoute =
  AdminInfrastructureIndexRouteImport.update({
    id: '/infrastructure/',
    path: '/infrastructure/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentHealthIndexRoute = AdminContentHealthIndexRouteImport.update({
  id: '/content-health/',
  path: '/content-health/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildersIndexRoute = AdminBuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmenitiesIndexRoute = AdminAmenitiesIndexRouteImport.update({
  id: '/amenities/',
  path: '/amenities/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnitTypesNewRoute = AdminUnitTypesNewRouteImport.update({
  id: '/unit-types/new',
  path: '/unit-types/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnitTypesIdRoute = AdminUnitTypesIdRouteImport.update({
  id: '/unit-types/$id',
  path: '/unit-types/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesNewRoute = AdminPlacesNewRouteImport.update({
  id: '/places/new',
  path: '/places/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesIdRoute = AdminPlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfrastructureNewRoute = AdminInfrastructureNewRouteImport.update({
  id: '/infrastructure/new',
  path: '/infrastructure/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfrastructureIdRoute = AdminInfrastructureIdRouteImport.update({
  id: '/infrastructure/$id',
  path: '/infrastructure/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIdRoute = AdminCategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildersNewRoute = AdminBuildersNewRouteImport.update({
  id: '/builders/new',
  path: '/builders/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildersIdRoute = AdminBuildersIdRouteImport.update({
  id: '/builders/$id',
  path: '/builders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmenitiesNewRoute = AdminAmenitiesNewRouteImport.update({
  id: '/amenities/new',
  path: '/amenities/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmenitiesIdRoute = AdminAmenitiesIdRouteImport.update({
  id: '/amenities/$id',
  path: '/amenities/$id',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/journey': typeof JourneyRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/builder/omaxe': typeof BuilderOmaxeRoute
  '/builders/$slug': typeof BuildersSlugRoute
  '/places/new-chandigarh': typeof PlacesNewChandigarhRoute
  '/project/hero-homes': typeof ProjectHeroHomesRoute
  '/admin/': typeof AdminIndexRoute
  '/builders/': typeof BuildersIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/amenities/$id': typeof AdminAmenitiesIdRoute
  '/admin/amenities/new': typeof AdminAmenitiesNewRoute
  '/admin/builders/$id': typeof AdminBuildersIdRoute
  '/admin/builders/new': typeof AdminBuildersNewRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/infrastructure/$id': typeof AdminInfrastructureIdRoute
  '/admin/infrastructure/new': typeof AdminInfrastructureNewRoute
  '/admin/places/$id': typeof AdminPlacesIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/unit-types/$id': typeof AdminUnitTypesIdRoute
  '/admin/unit-types/new': typeof AdminUnitTypesNewRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/admin/amenities/': typeof AdminAmenitiesIndexRoute
  '/admin/builders/': typeof AdminBuildersIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/content-health/': typeof AdminContentHealthIndexRoute
  '/admin/infrastructure/': typeof AdminInfrastructureIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/places/': typeof AdminPlacesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/relationships/': typeof AdminRelationshipsIndexRoute
  '/admin/unit-types/': typeof AdminUnitTypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/builder/omaxe': typeof BuilderOmaxeRoute
  '/builders/$slug': typeof BuildersSlugRoute
  '/places/new-chandigarh': typeof PlacesNewChandigarhRoute
  '/project/hero-homes': typeof ProjectHeroHomesRoute
  '/admin': typeof AdminIndexRoute
  '/builders': typeof BuildersIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/amenities/$id': typeof AdminAmenitiesIdRoute
  '/admin/amenities/new': typeof AdminAmenitiesNewRoute
  '/admin/builders/$id': typeof AdminBuildersIdRoute
  '/admin/builders/new': typeof AdminBuildersNewRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/infrastructure/$id': typeof AdminInfrastructureIdRoute
  '/admin/infrastructure/new': typeof AdminInfrastructureNewRoute
  '/admin/places/$id': typeof AdminPlacesIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/unit-types/$id': typeof AdminUnitTypesIdRoute
  '/admin/unit-types/new': typeof AdminUnitTypesNewRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/admin/amenities': typeof AdminAmenitiesIndexRoute
  '/admin/builders': typeof AdminBuildersIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/content-health': typeof AdminContentHealthIndexRoute
  '/admin/infrastructure': typeof AdminInfrastructureIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/places': typeof AdminPlacesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/relationships': typeof AdminRelationshipsIndexRoute
  '/admin/unit-types': typeof AdminUnitTypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/journey': typeof JourneyRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin_/login': typeof AdminLoginRoute
  '/builder/omaxe': typeof BuilderOmaxeRoute
  '/builders/$slug': typeof BuildersSlugRoute
  '/places/new-chandigarh': typeof PlacesNewChandigarhRoute
  '/project/hero-homes': typeof ProjectHeroHomesRoute
  '/admin/': typeof AdminIndexRoute
  '/builders/': typeof BuildersIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/amenities/$id': typeof AdminAmenitiesIdRoute
  '/admin/amenities/new': typeof AdminAmenitiesNewRoute
  '/admin/builders/$id': typeof AdminBuildersIdRoute
  '/admin/builders/new': typeof AdminBuildersNewRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/infrastructure/$id': typeof AdminInfrastructureIdRoute
  '/admin/infrastructure/new': typeof AdminInfrastructureNewRoute
  '/admin/places/$id': typeof AdminPlacesIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/unit-types/$id': typeof AdminUnitTypesIdRoute
  '/admin/unit-types/new': typeof AdminUnitTypesNewRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/admin/amenities/': typeof AdminAmenitiesIndexRoute
  '/admin/builders/': typeof AdminBuildersIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/content-health/': typeof AdminContentHealthIndexRoute
  '/admin/infrastructure/': typeof AdminInfrastructureIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/places/': typeof AdminPlacesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/relationships/': typeof AdminRelationshipsIndexRoute
  '/admin/unit-types/': typeof AdminUnitTypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/journey'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/builder/omaxe'
    | '/builders/$slug'
    | '/places/new-chandigarh'
    | '/project/hero-homes'
    | '/admin/'
    | '/builders/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/amenities/$id'
    | '/admin/amenities/new'
    | '/admin/builders/$id'
    | '/admin/builders/new'
    | '/admin/categories/$id'
    | '/admin/categories/new'
    | '/admin/infrastructure/$id'
    | '/admin/infrastructure/new'
    | '/admin/places/$id'
    | '/admin/places/new'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/admin/unit-types/$id'
    | '/admin/unit-types/new'
    | '/api/public/sitemap'
    | '/admin/amenities/'
    | '/admin/builders/'
    | '/admin/categories/'
    | '/admin/content-health/'
    | '/admin/infrastructure/'
    | '/admin/media/'
    | '/admin/places/'
    | '/admin/projects/'
    | '/admin/relationships/'
    | '/admin/unit-types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journey'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/builder/omaxe'
    | '/builders/$slug'
    | '/places/new-chandigarh'
    | '/project/hero-homes'
    | '/admin'
    | '/builders'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/amenities/$id'
    | '/admin/amenities/new'
    | '/admin/builders/$id'
    | '/admin/builders/new'
    | '/admin/categories/$id'
    | '/admin/categories/new'
    | '/admin/infrastructure/$id'
    | '/admin/infrastructure/new'
    | '/admin/places/$id'
    | '/admin/places/new'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/admin/unit-types/$id'
    | '/admin/unit-types/new'
    | '/api/public/sitemap'
    | '/admin/amenities'
    | '/admin/builders'
    | '/admin/categories'
    | '/admin/content-health'
    | '/admin/infrastructure'
    | '/admin/media'
    | '/admin/places'
    | '/admin/projects'
    | '/admin/relationships'
    | '/admin/unit-types'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/journey'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin_/login'
    | '/builder/omaxe'
    | '/builders/$slug'
    | '/places/new-chandigarh'
    | '/project/hero-homes'
    | '/admin/'
    | '/builders/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/amenities/$id'
    | '/admin/amenities/new'
    | '/admin/builders/$id'
    | '/admin/builders/new'
    | '/admin/categories/$id'
    | '/admin/categories/new'
    | '/admin/infrastructure/$id'
    | '/admin/infrastructure/new'
    | '/admin/places/$id'
    | '/admin/places/new'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/admin/unit-types/$id'
    | '/admin/unit-types/new'
    | '/api/public/sitemap'
    | '/admin/amenities/'
    | '/admin/builders/'
    | '/admin/categories/'
    | '/admin/content-health/'
    | '/admin/infrastructure/'
    | '/admin/media/'
    | '/admin/places/'
    | '/admin/projects/'
    | '/admin/relationships/'
    | '/admin/unit-types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BuilderOmaxeRoute: typeof BuilderOmaxeRoute
  BuildersSlugRoute: typeof BuildersSlugRoute
  PlacesNewChandigarhRoute: typeof PlacesNewChandigarhRoute
  ProjectHeroHomesRoute: typeof ProjectHeroHomesRoute
  BuildersIndexRoute: typeof BuildersIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/': {
      id: '/builders/'
      path: '/builders'
      fullPath: '/builders/'
      preLoaderRoute: typeof BuildersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/project/hero-homes': {
      id: '/project/hero-homes'
      path: '/project/hero-homes'
      fullPath: '/project/hero-homes'
      preLoaderRoute: typeof ProjectHeroHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/new-chandigarh': {
      id: '/places/new-chandigarh'
      path: '/places/new-chandigarh'
      fullPath: '/places/new-chandigarh'
      preLoaderRoute: typeof PlacesNewChandigarhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/$slug': {
      id: '/builders/$slug'
      path: '/builders/$slug'
      fullPath: '/builders/$slug'
      preLoaderRoute: typeof BuildersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/omaxe': {
      id: '/builder/omaxe'
      path: '/builder/omaxe'
      fullPath: '/builder/omaxe'
      preLoaderRoute: typeof BuilderOmaxeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unit-types/': {
      id: '/admin/unit-types/'
      path: '/unit-types'
      fullPath: '/admin/unit-types/'
      preLoaderRoute: typeof AdminUnitTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relationships/': {
      id: '/admin/relationships/'
      path: '/relationships'
      fullPath: '/admin/relationships/'
      preLoaderRoute: typeof AdminRelationshipsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places/': {
      id: '/admin/places/'
      path: '/places'
      fullPath: '/admin/places/'
      preLoaderRoute: typeof AdminPlacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infrastructure/': {
      id: '/admin/infrastructure/'
      path: '/infrastructure'
      fullPath: '/admin/infrastructure/'
      preLoaderRoute: typeof AdminInfrastructureIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-health/': {
      id: '/admin/content-health/'
      path: '/content-health'
      fullPath: '/admin/content-health/'
      preLoaderRoute: typeof AdminContentHealthIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builders/': {
      id: '/admin/builders/'
      path: '/builders'
      fullPath: '/admin/builders/'
      preLoaderRoute: typeof AdminBuildersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amenities/': {
      id: '/admin/amenities/'
      path: '/amenities'
      fullPath: '/admin/amenities/'
      preLoaderRoute: typeof AdminAmenitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unit-types/new': {
      id: '/admin/unit-types/new'
      path: '/unit-types/new'
      fullPath: '/admin/unit-types/new'
      preLoaderRoute: typeof AdminUnitTypesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unit-types/$id': {
      id: '/admin/unit-types/$id'
      path: '/unit-types/$id'
      fullPath: '/admin/unit-types/$id'
      preLoaderRoute: typeof AdminUnitTypesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places/new': {
      id: '/admin/places/new'
      path: '/places/new'
      fullPath: '/admin/places/new'
      preLoaderRoute: typeof AdminPlacesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places/$id': {
      id: '/admin/places/$id'
      path: '/places/$id'
      fullPath: '/admin/places/$id'
      preLoaderRoute: typeof AdminPlacesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infrastructure/new': {
      id: '/admin/infrastructure/new'
      path: '/infrastructure/new'
      fullPath: '/admin/infrastructure/new'
      preLoaderRoute: typeof AdminInfrastructureNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infrastructure/$id': {
      id: '/admin/infrastructure/$id'
      path: '/infrastructure/$id'
      fullPath: '/admin/infrastructure/$id'
      preLoaderRoute: typeof AdminInfrastructureIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/$id': {
      id: '/admin/categories/$id'
      path: '/categories/$id'
      fullPath: '/admin/categories/$id'
      preLoaderRoute: typeof AdminCategoriesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builders/new': {
      id: '/admin/builders/new'
      path: '/builders/new'
      fullPath: '/admin/builders/new'
      preLoaderRoute: typeof AdminBuildersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builders/$id': {
      id: '/admin/builders/$id'
      path: '/builders/$id'
      fullPath: '/admin/builders/$id'
      preLoaderRoute: typeof AdminBuildersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amenities/new': {
      id: '/admin/amenities/new'
      path: '/amenities/new'
      fullPath: '/admin/amenities/new'
      preLoaderRoute: typeof AdminAmenitiesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amenities/$id': {
      id: '/admin/amenities/$id'
      path: '/amenities/$id'
      fullPath: '/admin/amenities/$id'
      preLoaderRoute: typeof AdminAmenitiesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAmenitiesIdRoute: typeof AdminAmenitiesIdRoute
  AdminAmenitiesNewRoute: typeof AdminAmenitiesNewRoute
  AdminBuildersIdRoute: typeof AdminBuildersIdRoute
  AdminBuildersNewRoute: typeof AdminBuildersNewRoute
  AdminCategoriesIdRoute: typeof AdminCategoriesIdRoute
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminInfrastructureIdRoute: typeof AdminInfrastructureIdRoute
  AdminInfrastructureNewRoute: typeof AdminInfrastructureNewRoute
  AdminPlacesIdRoute: typeof AdminPlacesIdRoute
  AdminPlacesNewRoute: typeof AdminPlacesNewRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminUnitTypesIdRoute: typeof AdminUnitTypesIdRoute
  AdminUnitTypesNewRoute: typeof AdminUnitTypesNewRoute
  AdminAmenitiesIndexRoute: typeof AdminAmenitiesIndexRoute
  AdminBuildersIndexRoute: typeof AdminBuildersIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminContentHealthIndexRoute: typeof AdminContentHealthIndexRoute
  AdminInfrastructureIndexRoute: typeof AdminInfrastructureIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminPlacesIndexRoute: typeof AdminPlacesIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminRelationshipsIndexRoute: typeof AdminRelationshipsIndexRoute
  AdminUnitTypesIndexRoute: typeof AdminUnitTypesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAmenitiesIdRoute: AdminAmenitiesIdRoute,
  AdminAmenitiesNewRoute: AdminAmenitiesNewRoute,
  AdminBuildersIdRoute: AdminBuildersIdRoute,
  AdminBuildersNewRoute: AdminBuildersNewRoute,
  AdminCategoriesIdRoute: AdminCategoriesIdRoute,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminInfrastructureIdRoute: AdminInfrastructureIdRoute,
  AdminInfrastructureNewRoute: AdminInfrastructureNewRoute,
  AdminPlacesIdRoute: AdminPlacesIdRoute,
  AdminPlacesNewRoute: AdminPlacesNewRoute,
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminUnitTypesIdRoute: AdminUnitTypesIdRoute,
  AdminUnitTypesNewRoute: AdminUnitTypesNewRoute,
  AdminAmenitiesIndexRoute: AdminAmenitiesIndexRoute,
  AdminBuildersIndexRoute: AdminBuildersIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminContentHealthIndexRoute: AdminContentHealthIndexRoute,
  AdminInfrastructureIndexRoute: AdminInfrastructureIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminPlacesIndexRoute: AdminPlacesIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminRelationshipsIndexRoute: AdminRelationshipsIndexRoute,
  AdminUnitTypesIndexRoute: AdminUnitTypesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  JourneyRoute: JourneyRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminLoginRoute: AdminLoginRoute,
  BuilderOmaxeRoute: BuilderOmaxeRoute,
  BuildersSlugRoute: BuildersSlugRoute,
  PlacesNewChandigarhRoute: PlacesNewChandigarhRoute,
  ProjectHeroHomesRoute: ProjectHeroHomesRoute,
  BuildersIndexRoute: BuildersIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
