/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectHeroHomesRouteImport } from './routes/project.hero-homes'
import { Route as PlacesNewChandigarhRouteImport } from './routes/places.new-chandigarh'
import { Route as BuilderOmaxeRouteImport } from './routes/builder.omaxe'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AdminPlacesIndexRouteImport } from './routes/admin.places.index'
import { Route as AdminBuildersIndexRouteImport } from './routes/admin.builders.index'
import { Route as AdminPlacesNewRouteImport } from './routes/admin.places.new'
import { Route as AdminPlacesIdRouteImport } from './routes/admin.places.$id'
import { Route as AdminBuildersNewRouteImport } from './routes/admin.builders.new'
import { Route as AdminBuildersIdRouteImport } from './routes/admin.builders.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectHeroHomesRoute = ProjectHeroHomesRouteImport.update({
  id: '/project/hero-homes',
  path: '/project/hero-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesNewChandigarhRoute = PlacesNewChandigarhRouteImport.update({
  id: '/places/new-chandigarh',
  path: '/places/new-chandigarh',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderOmaxeRoute = BuilderOmaxeRouteImport.update({
  id: '/builder/omaxe',
  path: '/builder/omaxe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPlacesIndexRoute = AdminPlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildersIndexRoute = AdminBuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesNewRoute = AdminPlacesNewRouteImport.update({
  id: '/places/new',
  path: '/places/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesIdRoute = AdminPlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildersNewRoute = AdminBuildersNewRouteImport.update({
  id: '/builders/new',
  path: '/builders/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildersIdRoute = AdminBuildersIdRouteImport.update({
  id: '/builders/$id',
  path: '/builders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/journey': typeof JourneyRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/builder/omaxe': typeof BuilderOmaxeRoute
  '/places/new-chandigarh': typeof PlacesNewChandigarhRoute
  '/project/hero-homes': typeof ProjectHeroHomesRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/builders/$id': typeof AdminBuildersIdRoute
  '/admin/builders/new': typeof AdminBuildersNewRoute
  '/admin/places/$id': typeof AdminPlacesIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/builders/': typeof AdminBuildersIndexRoute
  '/admin/places/': typeof AdminPlacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/builder/omaxe': typeof BuilderOmaxeRoute
  '/places/new-chandigarh': typeof PlacesNewChandigarhRoute
  '/project/hero-homes': typeof ProjectHeroHomesRoute
  '/admin': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/builders/$id': typeof AdminBuildersIdRoute
  '/admin/builders/new': typeof AdminBuildersNewRoute
  '/admin/places/$id': typeof AdminPlacesIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/builders': typeof AdminBuildersIndexRoute
  '/admin/places': typeof AdminPlacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/journey': typeof JourneyRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin_/login': typeof AdminLoginRoute
  '/builder/omaxe': typeof BuilderOmaxeRoute
  '/places/new-chandigarh': typeof PlacesNewChandigarhRoute
  '/project/hero-homes': typeof ProjectHeroHomesRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/builders/$id': typeof AdminBuildersIdRoute
  '/admin/builders/new': typeof AdminBuildersNewRoute
  '/admin/places/$id': typeof AdminPlacesIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/builders/': typeof AdminBuildersIndexRoute
  '/admin/places/': typeof AdminPlacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/journey'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/builder/omaxe'
    | '/places/new-chandigarh'
    | '/project/hero-homes'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/builders/$id'
    | '/admin/builders/new'
    | '/admin/places/$id'
    | '/admin/places/new'
    | '/admin/builders/'
    | '/admin/places/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journey'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/builder/omaxe'
    | '/places/new-chandigarh'
    | '/project/hero-homes'
    | '/admin'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/builders/$id'
    | '/admin/builders/new'
    | '/admin/places/$id'
    | '/admin/places/new'
    | '/admin/builders'
    | '/admin/places'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/journey'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin_/login'
    | '/builder/omaxe'
    | '/places/new-chandigarh'
    | '/project/hero-homes'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/builders/$id'
    | '/admin/builders/new'
    | '/admin/places/$id'
    | '/admin/places/new'
    | '/admin/builders/'
    | '/admin/places/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BuilderOmaxeRoute: typeof BuilderOmaxeRoute
  PlacesNewChandigarhRoute: typeof PlacesNewChandigarhRoute
  ProjectHeroHomesRoute: typeof ProjectHeroHomesRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/project/hero-homes': {
      id: '/project/hero-homes'
      path: '/project/hero-homes'
      fullPath: '/project/hero-homes'
      preLoaderRoute: typeof ProjectHeroHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/new-chandigarh': {
      id: '/places/new-chandigarh'
      path: '/places/new-chandigarh'
      fullPath: '/places/new-chandigarh'
      preLoaderRoute: typeof PlacesNewChandigarhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/omaxe': {
      id: '/builder/omaxe'
      path: '/builder/omaxe'
      fullPath: '/builder/omaxe'
      preLoaderRoute: typeof BuilderOmaxeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/places/': {
      id: '/admin/places/'
      path: '/places'
      fullPath: '/admin/places/'
      preLoaderRoute: typeof AdminPlacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builders/': {
      id: '/admin/builders/'
      path: '/builders'
      fullPath: '/admin/builders/'
      preLoaderRoute: typeof AdminBuildersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places/new': {
      id: '/admin/places/new'
      path: '/places/new'
      fullPath: '/admin/places/new'
      preLoaderRoute: typeof AdminPlacesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places/$id': {
      id: '/admin/places/$id'
      path: '/places/$id'
      fullPath: '/admin/places/$id'
      preLoaderRoute: typeof AdminPlacesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builders/new': {
      id: '/admin/builders/new'
      path: '/builders/new'
      fullPath: '/admin/builders/new'
      preLoaderRoute: typeof AdminBuildersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builders/$id': {
      id: '/admin/builders/$id'
      path: '/builders/$id'
      fullPath: '/admin/builders/$id'
      preLoaderRoute: typeof AdminBuildersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBuildersIdRoute: typeof AdminBuildersIdRoute
  AdminBuildersNewRoute: typeof AdminBuildersNewRoute
  AdminPlacesIdRoute: typeof AdminPlacesIdRoute
  AdminPlacesNewRoute: typeof AdminPlacesNewRoute
  AdminBuildersIndexRoute: typeof AdminBuildersIndexRoute
  AdminPlacesIndexRoute: typeof AdminPlacesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBuildersIdRoute: AdminBuildersIdRoute,
  AdminBuildersNewRoute: AdminBuildersNewRoute,
  AdminPlacesIdRoute: AdminPlacesIdRoute,
  AdminPlacesNewRoute: AdminPlacesNewRoute,
  AdminBuildersIndexRoute: AdminBuildersIndexRoute,
  AdminPlacesIndexRoute: AdminPlacesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  JourneyRoute: JourneyRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminLoginRoute: AdminLoginRoute,
  BuilderOmaxeRoute: BuilderOmaxeRoute,
  PlacesNewChandigarhRoute: PlacesNewChandigarhRoute,
  ProjectHeroHomesRoute: ProjectHeroHomesRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
